# Generated by Django 4.2.21 on 2025-07-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista_professor',
            name='matriculaProfessor',
        ),
    ]
