# Generated by Django 4.2.21 on 2025-07-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_remove_lista_professor_matriculaprofessor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProfessor', models.CharField(max_length=100)),
                ('matriculaProfessor', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Lista_professor',
        ),
    ]
