# Generated by Django 4.2.21 on 2025-07-12 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_professor_delete_lista_professor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='professor',
            table='professor',
        ),
    ]
