# Generated by Django 4.2.21 on 2025-07-12 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_alter_professor_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='professor',
            table=None,
        ),
    ]
