# Generated by Django 4.2.21 on 2025-07-13 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_alter_professor_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
