# Generated by Django 4.2.21 on 2025-07-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0008_delete_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProfessor', models.CharField(max_length=100)),
                ('matriculaProfessor', models.IntegerField()),
            ],
        ),
    ]
