# Generated by Django 4.2.21 on 2025-07-13 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
