# Generated by Django 4.2.21 on 2025-07-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0011_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='administrador',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
