# Generated by Django 4.2.21 on 2025-07-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0012_remove_professor_administrador_delete_administrador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id_professor', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_professor', models.CharField(max_length=100)),
                ('senha_professor', models.CharField(max_length=15)),
                ('matricula_professor', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'professor',
                'managed': False,
            },
        ),
    ]
