# Generated by Django 4.2.21 on 2025-07-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0014_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_turma', models.CharField(max_length=50)),
                ('ano', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'turma',
                'managed': False,
            },
        ),
    ]
