# Generated by Django 4.2.21 on 2025-07-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0015_turma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={},
        ),
    ]
