# Generated by Django 4.2.21 on 2025-07-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0016_alter_aluno_options_alter_professor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'managed': False},
        ),
    ]
