# Generated by Django 4.2.21 on 2025-07-16 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0017_alter_aluno_options_alter_professor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id_avaliacao', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'avaliacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.FloatField(unique=True)),
                ('Avaliacao', models.ForeignKey(blank=True, db_column='id_avaliacao', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.avaliacao')),
                ('aluno', models.ForeignKey(blank=True, db_column='id_aluno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.aluno')),
            ],
        ),
    ]
