# Generated by Django 4.2.21 on 2025-07-16 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0018_avaliacao_nota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'managed': False},
        ),
    ]
