# Generated by Django 4.2.21 on 2025-07-16 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0019_alter_nota_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nota',
            table='nota',
        ),
    ]
